export const GAME_CONFIG = {
  seed: 133742,
  ship: {
    radius: 1,
    maxSpeed: 20,
    baseAcceleration: 4,
    depthAccelerationScale: 0.95,
    baseDrag: 0.24,
    turnDrag: 0.34,
    stallDrag: 1.35,
    speedLimitExtraDrag: 1.2,
    softTurnAngleDeg: 25,
    stallAngleDeg: 65,
    steeringResponsiveness: 5.2,
    thrustEfficiencyAtFullStall: 0.25,
    visualForwardTurnRateMin: 1.7,
    visualForwardTurnRateMax: 8.4,
    hp: 100.0,
    hitInvulnerabilityTime: 1,
  },
  camera: {
    distance: 8.5,
    height: 3.4,
    smoothness: 0.1,
    followLookDelay: 0.22,
    followLookDamping: 4.8,
    keyboardYawSpeed: 1.8,
    keyboardPitchSpeed: 1.45,
    deadlockHalfWidth: 0.65,
    deadlockHalfHeight: 0.4,
    thrustLookAssistStartAngleDeg: 12,
    thrustLookAssistFullAngleDeg: 42,
    thrustLookAssistSpeedThreshold: 7.5,
    thrustLookAssistMaxBlend: 0.72,
    fov: 68,
    pitchMin: -1.2,
    pitchMax: 1.2,
    // How many seconds of travel the camera looks ahead. Scales with ship speed
    // so at high speed the view opens up further ahead.
    lookAheadSeconds: 1.0,
    // Minimum look-ahead distance (units) when the ship is slow or stationary.
    lookAheadMin: 3,
    // Safety margin (fraction of half-FOV) keeping framed points away from screen edges.
    viewMargin: 0.12,
    // Points in ship-local space (x=right, y=up, z=forward/nose) that must always be visible.
    shipViewAnchors: [
      { x: 0, y: 0, z: 2.5 },   // nose
      { x: 0, y: 0, z: -1.5 },  // tail
    ],
  },
  world: {
    chunkSize: 64,
    interactiveRadius: 0,
    simulationRadius: 1,
    preloadRadiusPadding: 1,
    generationLookaheadSeconds: 4,
    spawnBudgetInitial: 10,
    spawnBudgetMin: 1,
    spawnBudgetFpsThreshold: 30,
    spawnBudgetSampleSeconds: 10,
    depthDifficultyRamp: 320,
    depthObstacleDensityBonus: 0.18,
    depthObstacleCapMultiplier: 1.45,
    depthCellDensityBonus: 0.2,
    spawn: {
      x: 32,
      y: 32,
      z: 32,
    },
    portalRadius: 4.5,
    portalInset: 2.2,
    portalThickness: 2,
    denseSplitDivisions: 3,
    sparseSplitDivisions: 2,
    octoboxMaxDepth: 4,
    octoboxSplitProbability: 0.82,
    octoboxMinCellSizeMultiplier: 1.15,
    octoboxMaxCellSizeMultiplier: 20,
    octoboxEmptyDensityThreshold: 0.12,
    octoboxDenseDensityThreshold: 0.58,
    freeBoxProbability: 0.18,
    minPassageRadius: 4,
    maxObstaclesPerChunk: 120,
    maxLootPerChunk: 20,
    chunkBuildWorkers: 2,
    generationMode: 'scatter',
    caveCoreBias: 0.72,
    caveWallBias: 0.6,
  },
  collision: {
    obstacleDamage: 34,
    largeObstacleDamage: 67,
    surfaceDamage: 20,
    separationDistance: 0.35,
    obstacleReboundFactor: 1.1,
    obstacleReboundMinSpeed: 8,
    obstacleTangentialDamping: 0.42,
    surfaceReboundFactor: 1.2,
    surfaceReboundMinSpeed: 10,
    surfaceTangentialDamping: 0.78,
    coinRadius: 1.5,
    chestRadius: 2.2,
  },
  mines: {
    maxPerChunk: 3,
    triggerRadius: 15,
    launchSpeed: 22,
    leadTime: 0.7,
    telegraphDuration: 0.5,
    radius: 1.2,
    damage: 34,
  },
  cave: {
    enabled: true,
    entranceProbability: 0.06,
    baseRadius: 5.5,
    minRadius: 3,
    radiusDecayPerDepth: 0.8,
    nodeSpacing: 14,
    minNodes: 3,
    maxNodes: 6,
    maxCurvature: 0.35,
    branchProbability: 0.4,
    maxBranchDepth: 2,
    gauntletSpacing: 10,
    ringSegments: 12,
    sampleStep: 2,
  },
  visuals: {
    debugEnabled: false,
    debugChunkRadius: 0,
    skyColor: 0x03111a,
    fogColor: 0x02070c,
    fogDensity: 0.012,
    fogVisibilityThreshold: 0.03,
  },
} as const;
