export const GAME_CONFIG = {
  seed: 133742,
  ship: {
    radius: 1,
    cruiseSpeed: 7.5,
    boostSpeed: 13.5,
    turnRateAtCruise: 7.5,
    turnRateAtBoost: 2.2,
    driftCorrectionAtCruise: 6.5,
    driftCorrectionAtBoost: 1.15,
    minSpeedFloor: 5.5,
    hp: 3,
    hitInvulnerabilityTime: 1,
  },
  camera: {
    distance: 10.5,
    height: 3.4,
    smoothness: 0.12,
    followLookDelay: 0.22,
    followLookDamping: 4.8,
    fov: 68,
    pitchMin: -1.2,
    pitchMax: 1.2,
  },
  world: {
    chunkSize: 64,
    activeRadius: 1,
    spawn: {
      x: 32,
      y: 32,
      z: 32,
    },
    portalRadius: 4.5,
    portalInset: 2.2,
    portalThickness: 2,
    splitDivisions: 3,
    octoboxMaxDepth: 5,
    octoboxSplitProbability: 0.82,
    octoboxMinCellSize: 3.5,
    freeBoxProbability: 0.18,
    minPassageRadius: 4,
    maxObstaclesPerChunk: 120,
    maxLootPerChunk: 20,
    chunkBuildWorkers: 2,
    generationMode: 'cave',
    caveCoreBias: 0.72,
    caveWallBias: 0.6,
  },
  collision: {
    obstacleDamage: 1,
    coinRadius: 1.5,
    chestRadius: 2.2,
  },
  visuals: {
    debugEnabled: true,
    skyColor: 0x03111a,
    fogColor: 0x02070c,
  },
} as const;
