import type { BoidsConfig, BoidVisualType, BoidTypeConfig } from './BoidsTypes'

export const DEFAULT_BOID_TYPE: BoidTypeConfig = {
  typeId: 0,
  name: 'smallFish',
  maxSpeed: 18,
  minSpeed: 4,
  perceptionRadius: 18,
  separationRadius: 6,
  separationWeight: 1.8,
  alignmentWeight: 0.8,
  cohesionWeight: 0.45,
  scale: 1.0,
}

export const DEFAULT_BOIDS_CONFIG: BoidsConfig = {
  enabled: true,
  maxBoids: 50000,
  initialBoids: 10000,
  simulationRadius: 400,
  renderRadius: 500,
  spawnRadius: 350,
  despawnRadius: 650,
  perceptionRadius: 18,
  separationRadius: 6,
  minSpeed: 4,
  maxSpeed: 18,
  maxForce: 8,
  turnRate: 3.5,
  separationWeight: 1.8,
  alignmentWeight: 0.8,
  cohesionWeight: 0.45,
  wallAvoidanceWeight: 2.8,
  flowWeight: 0.6,
  playerAvoidanceWeight: 2.0,
  avoidPlayerRadius: 25,
  gridCellSize: 18,
  maxBoidsPerCell: 128,
  visual: {
    type: 'fish' as BoidVisualType,
    scale: 1.0,
    animate: true,
    baseColor: 0x88ccff,
    emissiveStrength: 0.15,
    scaleVariation: 0.3,
    speedColoring: true,
    fogAware: true,
  },
  lod: {
    nearDistance: 120,
    midDistance: 280,
    farDistance: 500,
    cullDistance: 650,
  },
  fallback: {
    cpuMaxBoids: 3000,
  },
  boidTypes: [DEFAULT_BOID_TYPE],
}
